# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_LEDS_RTL)				+= led-regfield.o
obj-$(CONFIG_LEDS_RTL_SWITCHCORE_PORT)		+= rtl-switch-port-leds.o
obj-$(CONFIG_LEDS_RTL_SWITCHCORE_SYSTEM)	+= rtl-switch-sys-leds.o
